jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: jinmunan/jinmunan.github.io
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && export NODE_OPTIONS=--max_old_space_size=4096 && yarn build
          BUILD_DIR: src/.vuepress/dist
          CNAME: https://docs.klrss.com
